### ISSUE TITLE
General Checklist for Missing/Incorrect Data

### ISSUE THREAD

**Issue by jikaczmarski** [acep-uaf/ak-energy-statistics-2011_2021#14]
`2020_AK_Energy_Statistics.xslx`

- [ ] `Table 2.5a` Data from EIA861S needs to be scrutinized. Customer-level data are supposed to be imputed using share data from most recent EIA861 but in most cases, the cells result in  `#REF!`. Reporting names for those to examine are:
    - City & Borough of Sitka
    - Barrow Utilities & Electric Cooperative Inc.
    - City of Petersburg
    - City of Wrangell
- [ ] `Table 2.5a` Missing data from these communities: Stevens Village, Tuluksak, King Cove, Koyukuk, Diomede
- [ ] `Table 2.5a` Stevens Village and King Cove each have duplicate entries. No data though.
- [ ] `Table 1.j / Table 2.5a` Starting this year, the number of 'Other' customer accounts jumps from approximately 5,000 the year before to over 11,000 this year. Needs an explanation

`2015_AK_Energy_Statistics.xslx`

- [ ] Table 2.5a. Reporting name "Ekwok" is listed as being in the Southeast AEA energy region. It should be in Bristol Bay. Possible larger issue with intertie lookup tables? No lookup tables are included with this file.

`2014_AK_Energy_Statistics.xslx`

- [ ] Table 2.5a. Reporting name "Ekwok" is listed as being in the Southeast AEA energy region. It should be in Bristol Bay. Possible larger issue with intertie lookup tables? No lookup tables are included with this file.

**Comment by eldobbins** [comment]
migrated to errata file by #22
